config/routes.rb
Rails.application.routes.draw do
  root 'account/sessions#new'
  concern :deletable do
    member do
      get :delete
      put :publish
      put :withdraw
    end
  end
  
  concern :batch do
    collection do
      get :batch
      post :batch
    end
  end

  namespace :about do
    resources :audios
    resources :images
    resources :pages
    resources :videos
  end

  namespace :account do
    resources :sessions
    resources :users do
      member do
        get :password
        put :password
        get :setting
        put :setting
      end
      collection do
        get :ajaxValidateFieldName
        get :forget
        post :forget_mail
        get :reset_password
        post :reset_passwd
        get :reset_password_ok
      end
    end
  end

  namespace :admin do
    root 'application#index'
    namespace :about do
      root 'application#index'
      resources :audios, concerns: :deletable
      resources :images, concerns: :deletable
      resources :pages, concerns: :deletable
      resources :videos, concerns: :deletable
    end
    namespace :account do
      root 'application#index'
      resources :connections
      resources :sessions
      resources :users
    end
    namespace :admin do
      root 'application#index'
      resources :assignments
      resources :logs
      resources :permissions
      resources :roles
      resources :users
    end
    namespace :analytic do
      root 'application#index'
      resources :googles
      resources :statistics
    end
    namespace :message do
      root 'application#index'
      resources :emails
      resources :notifications
    end
    namespace :payment do
      root 'application#index'
      resources :currencies
      resources :platforms
      resources :transactions
    end
    namespace :travel do
      root 'application#index'
      resources :attributes, concerns: :deletable
      resources :categories, concerns: :deletable
      resources :cities, concerns: :deletable
      resources :comments
      resources :complaints
      resources :continents, concerns: :deletable
      resources :countries, concerns: :deletable
      resources :bookings do
        member do
          get :delete
          get :confirm
          post :confirm_data
          put :publish
          put :withdraw
        end
      end
      resources :favorites, concerns: :deletable
      resources :inventories, concerns: [:deletable, :batch]
      resources :journeys, concerns: :deletable
      resources :languages, concerns: :deletable
      resources :locations, concerns: :deletable
      resources :merchants, concerns: :deletable
      resources :products, concerns: :deletable
      resources :questions
      resources :refunds
      resources :services
      resources :tourists
    end
  end

  namespace :business do
    namespace :travel do
      resources :bookings do
        member do
          put :accept
          put :reject
        end
      end
      resources :complaints
      resources :inventories
      resources :journeys
      resources :merchants do
        collection do
          get :reg
        end
      end
      resources :photos
      resources :products do
        member do
          get :journeys
          get :complete
        end
      end
      resources :questions
    end
  end

  namespace :travel do
    resources :attributes
    resources :bookings do
      member do
        get :alipay_return
      end
    end
    resources :categories
    resources :cities
    resources :continents
    resources :costumers
    resources :countries
    resources :favorites
    resources :languages
    resources :locations
    resources :merchants
    resources :products
  end
  
  get '/about/statics(/*path)', to: 'about/statics#index'

end

app/models/travel.rb
module Travel
  def self.table_name_prefix
    'travel_'
  end
end

app/models/travel/attribute.rb
class Travel::Attribute < ActiveRecord::Base
  belongs_to :category
  has_many :parameters
  has_many :products, through: :parameters
  belongs_to :creator, class_name: Admin::User
  belongs_to :updater, class_name: Admin::User

  validates :name, uniqueness: true, allow_blank: true
  validates :sequence, numericality: { only_integer: true }, allow_nil: true
  validates :category, existence: true, allow_nil: true
  # validates :creator, existence: true, allow_nil: true
  # validates :updater, existence: true, allow_nil: true

  default_scope { where(active: true) }

  has_attached_file :icon, url: '/upload/travel/attribute/:id_partition/icon/:updated_at.:extension:style_extension'
  validates_attachment :icon_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }

  cattr_accessor :admin_fields
  self.admin_fields = %w[ category_id name description sequence options icon ]

  def deletable?
    parameters.empty?
  end
end

app/models/travel/booking.rb
class Travel::Booking < ActiveRecord::Base
  belongs_to :user, class_name: Account::User
  belongs_to :merchant
  belongs_to :product
  belongs_to :journey
  belongs_to :inventory

  validates :user, :merchant, :product, :journey, :inventory, existence: true
  validates :adult_number, :child_number, :total_price, numericality: { only_integer: true }
  validates :started_on, :name, :phone, :country, :state, :city, :address, :postcode, presence: true
  
  default_scope { where(active: true) }
  
  cattr_accessor :admin_fields
  self.admin_fields = %w[ confirm_text]
  
  before_validation do
    self.product_id = self.journey.product.id
    self.merchant_id = self.product.merchant.id
    self.total_price = self.adult_number.to_i * self.journey.inventories.find_by(started_on: self.started_on).try(:adult_price).to_i + self.child_number.to_i * self.journey.inventories.find_by(started_on: self.started_on).try(:child_price).to_i
    true
  end
  
  def alipay_checkout_url
    options = {
      subject: "##{self.id}",#{self.product.try(:name)}
      body: "##{self.id}",
      out_trade_no: self.id,
      service: 'create_direct_pay_by_user',
      total_fee: self.total_price,
      show_url: 'http://www.jilvtrip.com/',
      return_url: "http://www.jilvtrip.com/travel/bookings/#{self.id}/alipay_return",
      notify_url: "http://www.jilvtrip.com/travel/bookings/#{self.id}/alipay_return?source=notify",
      payment_type: '1',
    }
    alipay_url(options)
  end

private

  def alipay_url(options)
    options.merge!({
      _input_charset: 'utf-8',
      partner: CONFIG.alipay.account,
      seller_email: CONFIG.alipay.email,
    })
    puts options.sort.map{|k,v|"#{k}=#{v}"}.join("&")+CONFIG.alipay.key
    options.merge!({
      sign_type: 'MD5',
      sign: Digest::MD5.hexdigest(options.sort.map{|k,v|"#{k}=#{v}"}.join("&")+CONFIG.alipay.key),
    })
    action = "https://mapi.alipay.com/gateway.do"
    cgi_escape_action_and_options(action, options)
  end
  
  def cgi_escape_action_and_options(action, options)
    "#{action}?#{options.sort.map{|k, v| "#{CGI::escape(k.to_s)}=#{CGI::escape(v.to_s)}" }.join('&')}"
  end
end

app/models/travel/category.rb
class Travel::Category < ActiveRecord::Base
  belongs_to :parent, class_name: self
  has_many :children, class_name: self, foreign_key: 'parent_id'
  has_many :_attributes
  has_many :products
  belongs_to :creator, class_name: Admin::User
  belongs_to :updater, class_name: Admin::User

  validates :name, presence: true, allow_blank: true
  validates :sequence, numericality: { only_integer: true }, allow_nil: true
  validates :parent, existence: true, allow_nil: true
  # validates :creator, existence: true, allow_nil: true
  # validates :updater, existence: true, allow_nil: true

  default_scope { where(active: true) }

  has_attached_file :icon, url: '/upload/travel/category/:id_partition/icon/:updated_at.:extension:style_extension'
  validates_attachment :icon_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }
  has_attached_file :landscape, url: '/upload/travel/category/:id_partition/landscape/:updated_at.:extension:style_extension'
  validates_attachment :landscape_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }
  has_attached_file :background, url: '/upload/travel/category/:id_partition/background/:updated_at.:extension:style_extension'
  validates_attachment :background_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }

  cattr_accessor :admin_fields
  self.admin_fields = %w[ parent_id name description sequence icon landscape background ]

  def deletable?
    [children, _attributes, products].all(&:empty?)
  end
end

app/models/travel/city.rb
class Travel::City < ActiveRecord::Base
  belongs_to :country
  has_many :locations
  has_many :merchants
  has_many :products
  belongs_to :creator, class_name: Admin::User
  belongs_to :updater, class_name: Admin::User

  validates :name, uniqueness: true, allow_blank: true
  validates :sequence, numericality: { only_integer: true }, allow_nil: true
  validates :country, existence: true, allow_nil: true
  # validates :creator, existence: true, allow_nil: true
  # validates :updater, existence: true, allow_nil: true

  default_scope { where(active: true) }

  has_attached_file :icon, url: '/upload/travel/city/:id_partition/icon/:updated_at.:extension:style_extension'
  validates_attachment :icon_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }
  has_attached_file :landscape, url: '/upload/travel/city/:id_partition/landscape/:updated_at.:extension:style_extension'
  validates_attachment :landscape_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }
  has_attached_file :background, url: '/upload/travel/city/:id_partition/background/:updated_at.:extension:style_extension'
  validates_attachment :background_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }

  cattr_accessor :admin_fields
  self.admin_fields = %w[ country_id name description sequence icon landscape background ]

  def deletable?
    [locations, merchants, products].all?(&:empty?)
  end
end

app/models/travel/continent.rb
class Travel::Continent < ActiveRecord::Base
  has_many :countries
  has_many :merchants
  has_many :products
  belongs_to :creator, class_name: Admin::User
  belongs_to :updater, class_name: Admin::User

  validates :name, uniqueness: true, allow_blank: true
  validates :sequence, numericality: { only_integer: true }, allow_nil: true
  # validates :updater, existence: true, allow_nil: true
  # validates :creator, existence: true, allow_nil: true

  default_scope { where(active: true) }

  has_attached_file :icon, url: '/upload/travel/continent/:id_partition/icon/:updated_at.:extension:style_extension'
  validates_attachment :icon_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }
  has_attached_file :landscape, url: '/upload/travel/continent/:id_partition/landscape/:updated_at.:extension:style_extension'
  validates_attachment :landscape_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }
  has_attached_file :background, url: '/upload/travel/continent/:id_partition/background/:updated_at.:extension:style_extension'
  validates_attachment :background_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }

  cattr_accessor :admin_fields
  self.admin_fields = %w[ name description sequence icon landscape background ]

  def deletable?
    [countries, merchants, products].all?(&:empty?)
  end
end

app/models/travel/country.rb
class Travel::Country < ActiveRecord::Base
  belongs_to :continent
  has_many :cities
  has_many :merchants
  has_many :products
  belongs_to :creator, class_name: Admin::User
  belongs_to :updater, class_name: Admin::User

  validates :name, uniqueness: true, allow_blank: true
  validates :sequence, numericality: { only_integer: true }, allow_nil: true
  validates :phone_code, numericality: { only_integer: true }, uniqueness: true, allow_nil: true
  validates :continent, existence: true, allow_nil: true
  # validates :creator, existence: true, allow_nil: true
  # validates :updater, existence: true, allow_nil: true

  default_scope { where(active: true) }

  has_attached_file :icon, url: '/upload/travel/country/:id_partition/icon/:updated_at.:extension:style_extension'
  validates_attachment :icon_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }
  has_attached_file :landscape, url: '/upload/travel/country/:id_partition/landscape/:updated_at.:extension:style_extension'
  validates_attachment :landscape_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }
  has_attached_file :background, url: '/upload/travel/country/:id_partition/background/:updated_at.:extension:style_extension'
  validates_attachment :background_attachment, size: { in: 0..10.megabytes }, content_type: { content_type: %w[ image/jpeg image/jpg image/pjpeg image/png image/x-png image/gif ] }

  cattr_accessor :admin_fields
  self.admin_fields = %w[ continent_id name description sequence icon landscape background phone_code ]

  def deletable?
    [cities, merchants, products].all?(&:empty?)
  end

  def name_with_phone_code
    "#{name} | #{phone_code}"
  end
end

app/models/travel/favorite.rb
class Travel::Favorite < ActiveRecord::Base
  belongs_to :user, class_name: Account::User
  belongs_to :product

  validates :user, :product, existence: true

  default_scope { where active: true }
  
  cattr_accessor :admin_fields
  self.admin_fields = %w[ user_id product_id ]
end

app/models/travel/inventory.rb
class Travel::Inventory < ActiveRecord::Base
  belongs_to :journey
  belongs_to :product
  belongs_to :merchant
  has_many :bookings

  default_scope { where(active: true) }

  validates :journey, existence: true
  validates :started_on, presence: true
  validates :adult_price, :child_price, :total_number, :preserved_number, :remained_number, numericality: { only_integer: true }, allow_blank: true

  cattr_accessor :admin_fields, :business_fields
  self.business_fields = %w[ journey_id started_on adult_price child_price adult_mkt_price child_mkt_price total_number ]
  self.admin_fields = self.business_fields + %w[]
  
  before_validation do
    self.preserved_number ||= 0
    self.total_number = self.preserved_number if self.total_number.to_i < self.preserved_number.to_i
    self.remained_number = self.total_number.to_i - self.preserved_number.to_i
    self.product_id = self.journey.product.id
    self.merchant_id = self.journey.product.merchant.id
    true
  end
end

app/models/travel/journey.rb
class Travel::Journey < ActiveRecord::Base
  belongs_to :product
  belongs_to :merchant
  has_many :inventories

  default_scope { where(active: true) }

  validates :product_id, existence: true
  validates :name, :fee_description, :refund_policy, presence: true
  
  cattr_accessor :admin_fields, :business_fields
  self.business_fields = %w[ product_id name sequence lowest_price market_price adult_price child_price people_quota started_on ended_on start_time duration_time early_booking pick_up with_food introduction fee_description child_level refund_policy other_description route tips published ]
  self.admin_fields = self.business_fields + %w[]
  
  before_validation do
    self.merchant_id = self.product.merchant.id
    true
  end
end

app/models/travel/speaking.rb
class Travel::Speaking < ActiveRecord::Base
  belongs_to :product
  belongs_to :language
  
  # validates :language, existence: true

  default_scope { where(active: true) }
end

app/controllers/admin/travel/application_controller.rb
class Admin::Travel::ApplicationController < Admin::ApplicationController
end

app/controllers/admin/travel/attributes_controller.rb
class Admin::Travel::AttributesController < Admin::Travel::ApplicationController
  def index
    @attributes = model.default(params)
    @attributes = @attributes.limit(1) unless can?(:index, model)
    respond_with(@attributes)
  end

  def show
    @attribute = model.f(params[:id])
    respond_with(@attribute)
  end

  def new
    @attribute = model.new
    params[:travel_attribute] = model.f(params[:id]).attributes.merge(params[:travel_attribute].to_h) if params[:id]
    @attribute.attributes = params[:travel_attribute].to_h.slice(*model.admin_fields)
    render :show
  end

  def create
    @attribute = model.new
    @attribute.attributes = params[:travel_attribute].to_h.slice(*model.admin_fields).merge(creator_id: @current_user.id)
    @attribute.save
    render :show
  end

  def edit
    @attribute = model.f(params[:id])
    @attribute.attributes = params[:travel_attribute].to_h.slice(*model.admin_fields)
    render :show
  end

  def update
    @attribute = model.f(params[:id])
    @attribute.attributes = params[:travel_attribute].to_h.slice(*model.admin_fields).merge(updater_id: @current_user.id)
    @attribute.save

    respond_with(@attribute) do |format|
      format.html { render :show }
      format.js { head @attribute.valid? ? :accepted : :bad_request }
    end
  end
end

app/views/admin/travel/categories/_actions.html.slim
= link_to t('show'), [:admin, category] if can?(:show, category)
= link_to t('edit'), [:edit, :admin, category] if can?(:update, category)
= link_to t('delete'), [:delete, :admin, category], class: 'facebox' if can?(:destroy, category)
= link_to t('copy'), action: 'new', id: category.id if can?(:create, category) && can?(:show, category)
= link_to t('visit'), category

app/views/admin/travel/categories/index.html.slim
- @page_title = model.model_name.human
h2
  | #{model.model_name.human} #{t('list')} (#{@categories.total_entries}) &nbsp;
  = link_to t('new'), action: 'new' if can?(:create, model)
  = link_to t('visit'), model
= form_tag request.path, method: 'get', id: 'search_form' do
  .tablenav
    .alignleft
      = render 'admin/shared/search/array', field: 'id'
      = render 'admin/shared/search/like', field: 'name'
      = render 'admin/shared/search/basic', field: 'sequence'
      = render 'admin/shared/search/select', field: 'parent_id', options: model.order('sequence ASC, name ASC')
      = render 'admin/shared/search/range', field: 'created_at'
      = render 'admin/shared/search/range', field: 'updated_at'
      = render 'admin/shared/search/order', fields: %w[name sequence]
      = render 'admin/shared/search/page'
      = submit_tag t('search'), name: nil, class: 'button-secondary'
    br.clear
br.clear
table.widefat
  thead
    tr
      - %w[id name icon sequence parent_id children _attributes created_at updated_at actions published].each do |field|
        th = model.human_attribute_name(field)
  tbody
    - @categories.each do |category|
      tr
        td = category.id
        td = link_to_admin category
        td = image_tag category.icon.to_s, alt: '' if category.icon
        td = category.sequence
        td = link_to_admin category.parent
        td
          - category.children.order('sequence ASC, name ASC').each do |c|
            = link_to_admin c
        td = link_to_if can?(:show, category._attributes), category._attributes.size, admin_travel_attributes_path("where[category_id]" => category.id) if category._attributes.size > 0
        td = datetime_tag category.created_at
        td = datetime_tag category.updated_at
        td = render 'actions', category: category
        td = render 'admin/shared/publish', record: category
= render 'admin/shared/pagination'

app/views/admin/travel/categories/show.html.slim
- category = @category
- @page_title = "#{category.class.model_name.human} #{category.id} #{category.name}"
- show = params[:action] == 'show' || !%w[new edit].include?(params[:action]) && category.valid?

- if %w[create update destroy].include?(params[:action])
  - if category.valid?
    .updated
      p #{t(params[:action])} #{t('successful')}
  - else
    .error
      p #{t(params[:action])} #{t('failed')}
h2
  | #{t(show ? 'show' : category.new_record? ? 'new' : 'edit')} #{t(category.class.model_name.human)}
  span style='font-size:12px;' = render 'actions', category: category if show && category.active?
= form_for category, url: [:admin, category], method: category.new_record? ? :post : :put, html: { multipart: true } do |f|
  table.form-table
    tbody
      - if category.id?
        tr
          th = f.label :id
          td = category.id
      tr
        th = f.label :name
        td
          - if show
            = category.name
          - else
            = f.text_field :name
            = f.error_message_on :name
      tr
        th = f.label :description
        td
          - if show
            = text_format category.description
          - else
            = f.text_area :description
            = f.error_message_on :description
      tr
        th = f.label :sequence
        td
          - if show
            = category.sequence
          - else
            = f.text_field :sequence
            = f.error_message_on :sequence
      tr
        th = f.label :icon
        td
          - if show
            = image_tag category.icon.to_s, alt: '' if category.icon
          - else
            = f.file_field :icon
            = f.error_message_on :icon
      tr
        th = f.label :landscape
        td
          - if show
            = image_tag category.landscape.to_s, alt: '' if category.landscape
          - else
            = f.file_field :landscape
            = f.error_message_on :landscape
      tr
        th = f.label :background
        td
          - if show
            = image_tag category.background.to_s, alt: '' if category.background
          - else
            = f.file_field :background
            = f.error_message_on :background
      tr
        th = f.label :parent_id
        td
          - if show
            = link_to_admin category.parent
          - else
            = f.collection_select :parent_id, category.class.where(category.id && ['id != ?', category.id]).order('sequence ASC, name ASC'), :id, :name, include_blank: true
            = f.error_message_on :parent_id
      - if category.id?
        tr
          th = f.label :created_at
          td = category.created_at
        tr
          th = f.label :updated_at
          td = category.updated_at
        tr
          th = f.label :creator_id
          td = link_to_admin category.creator
        tr
          th = f.label :updater_id
          td = link_to_admin category.updater
  - unless show
    .submit = f.submit